ID: aws_pci_v321_config
Title: Config
DisplayCode: ""
Connector: ""
Description: ""
Children: []
Tags:
  pci:
  - "true"
  pci_version:
  - v3.2.1
  plugin:
  - aws
  service:
  - config
Managed: true
Enabled: true
AutoAssign: false
Baseline: true
Controls:
- aws_config_enabled_all_regions
