ID: application_insights_components_should_block_log_ingestion_and_querying_from_public_networks
Title: Application Insights components should block log ingestion and querying from public networks
Description: "Improve Application Insights security by blocking log ingestion and querying from public networks. Only private-link connected networks will be able to ingest and query logs of this component. Learn more at https://aka.ms/AzMonPrivateLink#configure-application-insights."
Query:
  ID: ""
  Engine: odysseus-v0.0.1
  QueryToExecute: ""
  Connector:
  - Azure
  PrimaryTable: null
  ListOfTables: []
  Parameters: []
  Global: false
ManualVerification: false
Severity: medium
Tags: {}
Managed: false
