ID: adaptive_application_controls_for_defining_safe_applications_should_be_enabled_on_your_machines
Title: Adaptive application controls for defining safe applications should be enabled on your machines
Description: Enable application controls to define the list of known-safe applications running on your machines, and alert you when other applications run. This helps harden your machines against malware. To simplify the process of configuring and maintaining your rules, Security Center uses machine learning to analyze the applications running on each machine and suggest the list of known-safe applications.
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: ""
  Connector:
  - Azure
  PrimaryTable: null
  ListOfTables: []
  Parameters: []
  Global: false
ManualVerification: false
Severity: high
Tags: {}
Managed: false
