ID: azure_app_service_environment_internal_encryption_enabled
Title: App Service Environment should enable internal encryption
Description: Setting InternalEncryption to true encrypts the pagefile, worker disks, and internal network traffic between the front ends and workers in an App Service Environment.
Query:
    ID: ""
    Engine: odysseus-v0.0.1
    QueryToExecute: "with app_service_environment as (\n  select\n    distinct id as id\n  from\n    azure_app_service_environment,\n    jsonb_array_elements(cluster_settings ) as s\n  where\n    s ->> 'name' = 'InternalEncryption'\n    and s ->> 'value' = 'true'\n)\nselect\n  a.id as resource,\n  a.kaytu_account_id as kaytu_account_id,\n  a.kaytu_resource_id as kaytu_resource_id,\n  case\n    when b.id is not null then 'ok'\n    else 'alarm'\n  end as status,\n  case\n    when b.id is not null then a.title || ' internal encryption enabled.'\n    else a.name || ' internal encryption disabled.'\n  end as reason\n  \n  , a.resource_group as resource_group\n  , sub.display_name as subscription\nfrom\n  azure_app_service_environment as a\n  left join app_service_environment as b on a.id = b.id,\n  azure_subscription as sub\nwhere\n  sub.subscription_id = a.subscription_id;\n"
    Connector: Azure
    PrimaryTable: azure_app_service_environment
    ListOfTables:
        - azure_app_service_environment
        - azure_subscription
    Parameters: []
ManualVerification: false
Severity: medium
Tags:
    nist_sp_800_53_rev_5:
        - "true"
    service:
        - Azure/AppService
Managed: false
