Description: Windows machines should have the specified Group Policy settings in the
  category 'Administrative Templates - Network' for guest logons, simultaneous connections,
  network bridge, ICS, and multicast name resolution. This policy requires that the
  Guest Configuration prerequisites have been deployed to the policy assignment scope.
  For details, visit https://aka.ms/gcpol.
ID: windows_machines_should_meet_requirements_for_'_administrative_templates_network'
Query:
  Connector: Azure
  Engine: odysseus-v0.0.1
  QueryToExecute: ''
Severity: medium
Title: Windows machines should meet requirements for 'Administrative Templates - Network'
