ID: audit_windows_machines_that_allow_re_use_of_the_passwords_after_the_specified_number_of_unique_passwords
Title: Audit Windows machines that allow re-use of the passwords after the specified number of unique passwords
Description: Requires that prerequisites are deployed to the policy assignment scope. For details, visit https://aka.ms/gcpol. Machines are non-compliant if Windows machines that allow re-use of the passwords after the specified number of unique passwords. Default value for unique passwords is 24
Query:
    ID: ""
    Engine: odysseus-v0.0.1
    QueryToExecute: ""
    Connector: Azure
    PrimaryTable: null
    ListOfTables: []
    Parameters: []
ManualVerification: false
Severity: medium
Tags: {}
Managed: false
