ID: audit_windows_machines_that_do_not_have_the_password_complexity_setting_enabled
Title: Audit Windows machines that do not have the password complexity setting enabled
Description: Requires that prerequisites are deployed to the policy assignment scope. For details, visit https://aka.ms/gcpol. Machines are non-compliant if Windows machines that do not have the password complexity setting enabled
Query:
    ID: ""
    Engine: odysseus-v0.0.1
    QueryToExecute: ""
    Connector: Azure
    PrimaryTable: null
    ListOfTables: []
    Parameters: []
ManualVerification: false
Severity: high
Tags: {}
Managed: false
