Description: To protect the privacy of information communicated over the Internet,
  your machines should use the latest version of the industry-standard cryptographic
  protocol, Transport Layer Security (TLS). TLS secures communications over a network
  by encrypting a connection between machines.
ID: windows_machines_should_be_configured_to_use_secure_communication_protocols
Query:
  Connector: Azure
  Engine: odysseus-v0.0.1
  QueryToExecute: ''
Severity: ''
Title: Windows machines should be configured to use secure communication protocols
