ID: audit_linux_machines_that_allow_remote_connections_from_accounts_without_passwords
Title: Audit Linux machines that allow remote connections from accounts without passwords
Description: Requires that prerequisites are deployed to the policy assignment scope. For details, visit https://aka.ms/gcpol. Machines are non-compliant if Linux machines that allow remote connections from accounts without passwords
Query:
  ID: ""
  Engine: odysseus-v0.0.1
  QueryToExecute: ""
  Connector:
  - Azure
  PrimaryTable: null
  ListOfTables: []
  Parameters: []
  Global: false
ManualVerification: false
Severity: high
Tags: {}
Managed: false
