ID: windows_machines_should_be_configured_to_use_secure_communication_protocols
Title: Windows machines should be configured to use secure communication protocols
Description: To protect the privacy of information communicated over the Internet, your machines should use the latest version of the industry-standard cryptographic protocol, Transport Layer Security (TLS). TLS secures communications over a network by encrypting a connection between machines.
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: ""
  Connector:
  - Azure
  PrimaryTable: null
  ListOfTables: []
  Parameters: []
  Global: false
ManualVerification: false
Severity: high
Tags: {}
Managed: false
