Description: Requires that prerequisites are deployed to the policy assignment scope.
  For details, visit https://aka.ms/gcpol. Machines are non-compliant if the Chef
  InSpec resource indicates that one or more of the packages provided by the parameter
  are not installed.
ID: audit_linux_machines_that_don't_have_the_specified_applications_installed
Query:
  Connector: Azure
  Engine: odysseus-v0.0.1
  QueryToExecute: ''
Severity: medium
Title: Audit Linux machines that don't have the specified applications installed
