Description: Requires that prerequisites are deployed to the policy assignment scope.
  For details, visit https://aka.ms/gcpol. Machines are non-compliant if Linux machines
  that do not have the passwd file permissions set to 0644
ID: audit_linux_machines_that_do_not_have_the_passwd_file_permissions_set_to_0644
Query:
  Connector: Azure
  Engine: odysseus-v0.0.1
  QueryToExecute: ''
Severity: ''
Title: Audit Linux machines that do not have the passwd file permissions set to 0644
