Description: Requires that prerequisites are deployed to the policy assignment scope.
  For details, visit https://aka.ms/gcpol. Machines are non-compliant if Windows machines
  that do not restrict the minimum password length to specified number of characters.
  Default value for minimum password length is 14 characters
ID: audit_windows_machines_that_do_not_restrict_the_minimum_password_length_to_specified_number_of_characters
Query:
  Connector: Azure
  Engine: odysseus-v0.0.1
  QueryToExecute: ''
Severity: ''
Title: Audit Windows machines that do not restrict the minimum password length to
  specified number of characters
