ID: windows_machines_should_meet_requirements_for_'_windows_firewall_properties'
Title: Windows machines should meet requirements for 'Windows Firewall Properties'
Description: Windows machines should have the specified Group Policy settings in the category 'Windows Firewall Properties' for firewall state, connections, rule management, and notifications. This policy requires that the Guest Configuration prerequisites have been deployed to the policy assignment scope. For details, visit https://aka.ms/gcpol.
Query:
  ID: ""
  Engine: odysseus-v0.0.1
  QueryToExecute: ""
  Connector:
  - Azure
  PrimaryTable: null
  ListOfTables: []
  Parameters: []
  Global: false
ManualVerification: false
Severity: medium
Tags: {}
Managed: false
