ID: audit_linux_machines_that_do_not_have_the_passwd_file_permissions_set_to_0644
Title: Audit Linux machines that do not have the passwd file permissions set to 0644
Description: Requires that prerequisites are deployed to the policy assignment scope. For details, visit https://aka.ms/gcpol. Machines are non-compliant if Linux machines that do not have the passwd file permissions set to 0644
Query:
    ID: ""
    Engine: odysseus-v0.0.1
    QueryToExecute: ""
    Connector: Azure
    PrimaryTable: null
    ListOfTables: []
    Parameters: []
ManualVerification: false
Severity: medium
Tags: {}
Managed: false
