ID: windows_machines_should_meet_requirements_for_'_security_options_network_security'
Title: Windows machines should meet requirements for 'Security Options - Network Security'
Description: Windows machines should have the specified Group Policy settings in the category 'Security Options - Network Security' for including Local System behavior, PKU2U, LAN Manager, LDAP client, and NTLM SSP. This policy requires that the Guest Configuration prerequisites have been deployed to the policy assignment scope. For details, visit https://aka.ms/gcpol.
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: ""
  Connector:
  - Azure
  PrimaryTable: null
  ListOfTables: []
  Parameters: []
  Global: false
ManualVerification: false
Severity: medium
Tags: {}
Managed: false
