ID: windows_machines_should_meet_requirements_for_'_system_audit_policies_privilege_use'
Title: Windows machines should meet requirements for 'System Audit Policies - Privilege Use'
Description: Windows machines should have the specified Group Policy settings in the category 'System Audit Policies - Privilege Use' for auditing nonsensitive and other privilege use. This policy requires that the Guest Configuration prerequisites have been deployed to the policy assignment scope. For details, visit https://aka.ms/gcpol.
Query:
  ID: ""
  Engine: odysseus-v0.0.1
  QueryToExecute: ""
  Connector:
  - Azure
  PrimaryTable: null
  ListOfTables: []
  Parameters: []
  Global: false
ManualVerification: false
Severity: medium
Tags: {}
Managed: false
