Description: Requires that prerequisites are deployed to the policy assignment scope.
  For details, visit https://aka.ms/gcpol. Machines are non-compliant if Windows machines
  that do not store passwords using reversible encryption
ID: audit_windows_machines_that_do_not_store_passwords_using_reversible_encryption
Query:
  Connector: Azure
  Engine: odysseus-v0.0.1
  QueryToExecute: ''
Severity: ''
Title: Audit Windows machines that do not store passwords using reversible encryption
