ID: audit_windows_machines_that_do_not_have_the_minimum_password_age_set_to_specified_number_of_days
Title: Audit Windows machines that do not have the minimum password age set to specified number of days
Description: Requires that prerequisites are deployed to the policy assignment scope. For details, visit https://aka.ms/gcpol. Machines are non-compliant if Windows machines that do not have the minimum password age set to specified number of days. Default value for minimum password age is 1 day
Query:
    ID: ""
    Engine: odysseus-v0.0.1
    QueryToExecute: ""
    Connector: Azure
    PrimaryTable: null
    ListOfTables: []
    Parameters: []
ManualVerification: false
Severity: high
Tags: {}
Managed: false
