Description: Windows machines should have the specified Group Policy settings in the
  category 'Security Options - User Account Control' for mode for admins, behavior
  of elevation prompt, and virtualizing file and registry write failures. This policy
  requires that the Guest Configuration prerequisites have been deployed to the policy
  assignment scope. For details, visit https://aka.ms/gcpol.
ID: windows_machines_should_meet_requirements_for_'_security_options_user_account_control'
Query:
  Connector: Azure
  Engine: odysseus-v0.0.1
  QueryToExecute: ''
Severity: medium
Title: Windows machines should meet requirements for 'Security Options - User Account
  Control'
