Description: Requires that prerequisites are deployed to the policy assignment scope.
  For details, visit https://aka.ms/gcpol. Machines are non-compliant if the machine
  is not configured correctly for one of the recommendations in the Azure compute
  security baseline.
ID: linux_machines_should_meet_requirements_for_the_azure_compute_security_baseline
Query:
  Connector: Azure
  Engine: odysseus-v0.0.1
  QueryToExecute: ''
Severity: ''
Title: Linux machines should meet requirements for the Azure compute security baseline
