Description: This control checks if an AWS CodeBuild project environment has privileged mode enabled. This control fails when an AWS CodeBuild project environment has privileged mode enabled.
ID: aws_codebuild_project_environment_privileged_mode_disabled
Managed: true
ManualVerification: false
Query:
  Connector: AWS
  Engine: odysseus-v0.0.1
  ListOfTables:
  - aws_codebuild_project
  PrimaryTable: aws_codebuild_project
  QueryToExecute: |
    select
      arn as resource,
      kaytu_account_id as kaytu_account_id,
      kaytu_resource_id as kaytu_resource_id,
      case
        when environment ->> 'PrivilegedMode' = 'true' then 'alarm'
        else 'ok'
      end as status,
      case
        when environment ->> 'PrivilegedMode' = 'true' then title || ' environment privileged mode enabled.'
        else title || ' environment privileged mode disabled.'
      end as reason
      
      , region, account_id
    from
      aws_codebuild_project;
Severity: ""
Tags:
  category:
  - Compliance
  cis_controls_v8_ig1:
  - "true"
  nist_csf:
  - "true"
  pci_dss_v321:
  - "true"
  plugin:
  - aws
  service:
  - AWS/CodeBuild
Title: CodeBuild project environments should not have privileged mode enabled
