ID: aws_elb_application_lb_drop_http_headers
Title: ELB application load balancers should be drop HTTP headers
Description: Ensure that your Elastic Load Balancers (ELB) are configured to drop http headers.
Query:
    ID: ""
    Engine: odysseus-v0.0.1
    QueryToExecute: "select\n  arn as resource,\n  kaytu_account_id as kaytu_account_id,\n  kaytu_resource_id as kaytu_resource_id,\n  case\n    when load_balancer_attributes @> '[{\"Key\": \"routing.http.drop_invalid_header_fields.enabled\", \"Value\": \"true\"}]' then 'ok'\n    else 'alarm'\n  end as status,\n  case\n    when load_balancer_attributes @> '[{\"Key\": \"routing.http.drop_invalid_header_fields.enabled\", \"Value\": \"true\"}]' then title || ' configured to drop http headers.'\n    else title || ' not configured to drop http headers.'\n  end as reason\n  \n  , region, account_id\nfrom\n  aws_ec2_application_load_balancer;\n"
    Connector: AWS
    PrimaryTable: aws_ec2_application_load_balancer
    ListOfTables:
        - aws_ec2_application_load_balancer
    Parameters: []
ManualVerification: false
Severity: medium
Tags:
    category:
        - Compliance
    fedramp_low_rev_4:
        - "true"
    gdpr:
        - "true"
    hipaa_final_omnibus_security_rule_2013:
        - "true"
    hipaa_security_rule_2003:
        - "true"
    nist_800_53_rev_4:
        - "true"
    nist_800_171_rev_2:
        - "true"
    nist_csf:
        - "true"
    pci_dss_v321:
        - "true"
    plugin:
        - aws
    rbi_cyber_security:
        - "true"
    service:
        - AWS/ELB
    soc_2:
        - "true"
Managed: false
