ID: aws_lambda_function_dead_letter_queue_configured
Title: Lambda functions should be configured with a dead-letter queue
Description: Enable this rule to help notify the appropriate personnel through Amazon Simple Queue Service (Amazon SQS) or Amazon Simple Notification Service (Amazon SNS) when a function has failed.
Query:
    ID: ""
    Engine: odysseus-v0.0.1
    QueryToExecute: "select\n  arn as resource,\n  kaytu_account_id as kaytu_account_id,\n  kaytu_resource_id as kaytu_resource_id,\n  case\n    when dead_letter_config_target_arn is null then 'alarm'\n    else 'ok'\n  end as status,\n  case\n    when dead_letter_config_target_arn is null then title || ' configured with dead-letter queue.'\n    else title || ' not configured with dead-letter queue.'\n  end as reason\n  \n  , region, account_id\nfrom\n  aws_lambda_function;\n"
    Connector: AWS
    PrimaryTable: aws_lambda_function
    ListOfTables:
        - aws_lambda_function
    Parameters: []
ManualVerification: false
Severity: medium
Tags:
    category:
        - Compliance
    fedramp_low_rev_4:
        - "true"
    fedramp_moderate_rev_4:
        - "true"
    ffiec:
        - "true"
    hipaa_final_omnibus_security_rule_2013:
        - "true"
    hipaa_security_rule_2003:
        - "true"
    nist_800_53_rev_5:
        - "true"
    nist_800_171_rev_2:
        - "true"
    nist_csf:
        - "true"
    plugin:
        - aws
    service:
        - AWS/Lambda
    soc_2:
        - "true"
Managed: false
