Description: AWS Config is a web service that performs configuration management of supported AWS resources within your account and delivers log files to you. The recorded information includes the configuration item (AWS resource), relationships between configuration items (AWS resources), any configuration changes between resources. It is recommended to enable AWS Config be enabled in all regions.
DocumentURI: ""
ID: aws_config_enabled_all_regions
Managed: true
ManualVerification: false
Query:
  Connector: AWS
  Engine: odysseus-v0.0.1
  ListOfTables:
  - aws_config_configuration_recorder
  - aws_region
  PrimaryTable: aws_region
  QueryToExecute: |
    -- pgFormatter-ignore
    -- Get count for any region with all matching criteria
    with global_recorders as (
      select
        count(*) as global_config_recorders
      from
        aws_config_configuration_recorder
      where
        recording_group -> 'IncludeGlobalResourceTypes' = 'true'
        and recording_group -> 'AllSupported' = 'true'
        and status ->> 'Recording' = 'true'
        and status ->> 'LastStatus' = 'SUCCESS'
    )
    select
      'arn:aws::' || a.region || ':' || a.account_id as resource,
      a.kaytu_account_id as kaytu_account_id,
      a.kaytu_resource_id as kaytu_resource_id,
      case
      -- When any of the region satisfies with above CTE
      -- In left join of <aws_config_configuration_recorder> table, regions now having
      -- 'Recording' and 'LastStatus' matching criteria can be considered as OK
        when
          g.global_config_recorders >= 1
          and status ->> 'Recording' = 'true'
          and status ->> 'LastStatus' = 'SUCCESS'
        then 'ok'
      -- Skip any regions that are disabled in the account.
        when a.opt_in_status = 'not-opted-in' then 'skip'
        else 'alarm'
      end as status,
      -- Below cases are for citing respective reasons for control state
      case
        when a.opt_in_status = 'not-opted-in' then a.region || ' region is disabled.'
        else
      case
        when recording_group -> 'IncludeGlobalResourceTypes' = 'true' then a.region || ' IncludeGlobalResourceTypes enabled,'
        else a.region || ' IncludeGlobalResourceTypes disabled,'
      end ||
      case
        when recording_group -> 'AllSupported' = 'true' then ' AllSupported enabled,'
        else ' AllSupported disabled,'
      end ||
      case
        when status ->> 'Recording' = 'true' then ' Recording enabled'
        else ' Recording disabled'
      end ||
      case
        when status ->> 'LastStatus' = 'SUCCESS' then ' and LastStatus is SUCCESS.'
        else ' and LastStatus is not SUCCESS.'
      end
      end as reason
      , a.region, a.account_id
    from
      global_recorders as g,
      aws_region as a
      left join aws_config_configuration_recorder as r on r.account_id = a.account_id and r.region = a.name;
Severity: high
Tags:
  category:
  - Compliance
  cis:
  - "true"
  cis_item_id:
  - "2.5"
  cis_level:
  - "1"
  cis_section_id:
  - "2"
  cis_type:
  - scored
  cis_version:
  - v1.2.0
  plugin:
  - aws
  service:
  - AWS/Config
  x-kaytu-explanation:
  - "AWS Config is a fully managed service that provides you with an AWS resource inventory, in order to manage configuration history and configuration change notifications. It essentially checks the compliance with desired configurations you've set.\n\n## **AWS Config**\n- AWS Config is a web service that allows you to manage the configuration of **supported AWS resources** within your account. AWS Config keeps track of the relationships between resources as well as any changes in configuration between resources.\n\n- The information recorded includes the configuration item (the AWS resource), relationships between configuration items (AWS resources), and any configuration changes between resources.\n\n- For improved compliance and optimization, it is advised that AWS Config be activated in all regions. This allows for superior tracking and management of resources and changes.\n\n- It delivers all the relevant log files to you, delivering a detailed view of resource configuration history, which can assist in troubleshooting, asset tracking and more. \n\n- AWS Config simplifies compliance auditing, security analysis, change management, and operational troubleshooting.\n\n- It prepares a comprehensive inventory of your AWS resources and their current configuration while continuously recording configuration changes.\n\n- With AWS Config, you can review changes in configurations and relationships between AWS resources, dive into detailed resource configuration histories, and decide on desired resource configuration states. \n\nOverall, AWS Config is crucial for maintaining system integrity, checking historical configuration details, and maintaining a track record of configuration history."
  x-kaytu-noncompliance-cost:
  - |-
    Cost of Non-Compliance:

    1. **Security Problems:** If AWS Config is not enabled across all regions, it leaves loopholes in your infrastructure that attackers can exploit. This can lead to data theft, manipulation, or even a complete system shutdown.

    2. **Regulatory Violations:** Many compliance regulations require companies to have a full visibility into their resource configuration and changes. Hence, not using AWS Config might lead to violations of such rules, resulting in hefty fines and penalties.

    3. **Audit Challenges:** Without AWS Config, auditing becomes a difficult task as the auditors won't have a comprehensive and consistent view of the resource configuration and changes made overtime. It might lead to more time and resources spent in audit processes.

    4. **Troubleshooting Difficulty:** It becomes difficult to troubleshoot problems without knowing the historical changes of AWS resources. It can cause longer downtime, impacting service availability.

    5. **Cost Management Challenges:** AWS Config helps maintain an optimum utilization of resources by tracking their configuration and usage. Without it, it would be challenging to manage costs effectively. 

    6. **Loss of Governance:** AWS Config allows businesses to govern their AWS resources efficiently. Without Config, they lose visibility and control over their resources, which can lead to inefficient resource management.
  x-kaytu-usefulness-example:
  - |
    ```markdown
    AWS Config is an incredibly useful tool for system administrators, developers, and auditors. Here's an example of how it can be used:

    Our new Chief Information Security Officer (CISO) in a financial services company comes on board and wants to understand the company's current security setup in AWS to make sure it meets regulatory requirements.

    The company’s AWS infrastructure spans multiple regions, and various departments manage resources. We have our databases in RDS, applications running on EC2, S3 buckets for data storage, and use various other AWS services. 

    By using AWS Config, our CISO can rapidly gain insights into the current state of resources across all regions. They will receive configuration details, including relationships between resources and changes over time. 

    AWS Config would show, for example, what security groups are associated with EC2 instances, which Amazon RDS databases are publicly accessible, or which IAM policies allow broad permissions to an Amazon S3 bucket.

    If a resource's configuration changes - say an S3 bucket's permissions is updated to grant public read access - Config would record this change, providing a full audit trail of configuration changes.

    Enabling AWS Config in all regions ensures no resources are left untracked. In this scenario, it's also critical to ensure regulatory compliance given the company's presence in the financial services sector.

    In essence, AWS Config grants our new CISO comprehensive visibility into the company's AWS environment, assisting them to ensure that resources are configured according to both AWS best practices and regulatory standards.
    ```
Title: Ensure AWS Config is enabled in all regions
