ID: aws_api_gwv2_authorization_type_configured
Title: API Gatewayv2 API routes should have an authorization type set
Description: Checks if Amazon API Gatewayv2 API routes have an authorization type set. This rule is ALARM if the authorization type is NONE.
Query:
  ID: ""
  Engine: odysseus-v0.0.1
  QueryToExecute: |
    SELECT
      route_key as resource,
      kaytu_resource_id,
      kaytu_account_id,
      CASE
        WHEN authorization_type = 'NONE' THEN 'alarm'
        ELSE 'ok'
      END as status,
      CASE
        WHEN authorization_type = 'NONE' THEN route_key || 'does not have any authorization'
        ELSE route_key || 'does have ' || authorization_type || ' authorization' 
      END as reason
    FROM 
      aws_api_gatewayv2_route
  Connector:
  - AWS
  PrimaryTable: aws_api_gatewayv2_route
  ListOfTables:
  - aws_api_gatewayv2_route
  Parameters: []
  Global: false
ManualVerification: false
Severity: low
Tags: {}
Managed: false
