connectors:
- AWS
name: Managed Airflow
query: select connection_id, region, count(*) from kaytu_lookup where resource_type = 'aws::mwaa::environment' group by 1,2;
status: active
tags:
  category:
  - Managed Services
