connectors:
- AWS
name: Elastic Beanstalk Web Application Service
query: select connection_id, region, count(*) from kaytu_lookup where resource_type = 'aws::elasticbeanstalk::application' group by 1,2;
status: active
tags:
  category:
  - PaaS
