connectors:
- Azure
name: Application gateway
query: select connection_id, region, count(*) from kaytu_lookup where resource_type = 'microsoft.network/applicationgateways' group by 1,2;
status: active
tags:
  category:
  - Networking
