connectors:
- Azure
name: Automation
query: select connection_id, region, count(*) from kaytu_lookup where resource_type IN ('microsoft.automation/automationaccounts') group by 1,2;
status: invisible
tags:
  category:
  - General
