connectors:
- AWS
name: Web Application Firewall (WAF)
query: select connection_id, region, count(*) from kaytu_lookup where resource_type IN ('aws::waf::webacl','aws::wafv2::webacl') group by 1,2;
status: invisible
tags:
  category:
  - Network
