Connector: AWS
Engine: odysseus-v0.0.1
ID: aws_insight_elb_application_lb_waf_enabled
ListOfTables:
- aws_ec2_application_load_balancer
PrimaryTable: aws_ec2_application_load_balancer
QueryToExecute: |-
  select
    -- Required Columns
    arn as resource, account_id, kaytu_account_id, kaytu_resource_id,
    case
      when load_balancer_attributes @> '[{"Key":"waf.fail_open.enabled","Value":"true"}]' then 'ok'
      else 'alarm'
    end as status,
    case
      when load_balancer_attributes @> '[{"Key":"waf.fail_open.enabled","Value":"true"}]' then title || ' WAF enabled.'
      else title || ' WAF disabled.'
    end as reason,
    -- Additional Dimensions
    region 
  from
    aws_ec2_application_load_balancer;
