ID: aws_foundational_security_config
Title: Config
ReferenceCode: ""
Description: ""
Children: []
Tags:
  aws_foundational_security:
  - "true"
  category:
  - Compliance
  plugin:
  - aws
  service:
  - AWS/Config
  type:
  - Benchmark
Managed: false
Enabled: true
AutoAssign: false
Baseline: false
Controls:
- aws_config_enabled_all_regions
