ID: aws_foundational_security_config
Title: Config
DisplayCode: ""
Connector: AWS
Description: ""
Children: []
Tags:
  aws_foundational_security:
  - "true"
  category:
  - Compliance
  plugin:
  - aws
  service:
  - AWS/Config
  type:
  - Benchmark
Enabled: true
Controls:
- aws_config_enabled_all_regions
